# Generated by Django 3.2.25 on 2024-07-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('description', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'api_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codigoscpv',
            fields=[
                ('id_cpv', models.AutoField(primary_key=True, serialize=False)),
                ('num_cpv', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=500)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'CodigosCPV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpvlicitacion',
            fields=[
                ('id_combinacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CPVLicitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('siglas', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Criterios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
                ('nif', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('pyme', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'Estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licitaciones',
            fields=[
                ('id_licitacion', models.AutoField(primary_key=True, serialize=False)),
                ('num_expediente', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('abonos_cuenta', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('clasificacion_subgrupo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('clasificacion_grupo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('clasificacion_cat', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('importe_con_impuestos', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('importe_sin_impuestos', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('criterios_economica', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('criterios_tecnica', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('criterios_valores_anormales', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('condiciones_especiales', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('infraccion_grave', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('contratacion_control', models.BooleanField(blank=True, null=True)),
                ('crit_adjudicacion', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('fecha_adjudicacion', models.DateField(blank=True, null=True)),
                ('fecha_formalizacion', models.DateField(blank=True, null=True)),
                ('fecha_anuncio', models.DateField(blank=True, null=True)),
                ('forma_pago', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('garantia_def', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('garantia_prov', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('gastos_desistimiento', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('modificaciones_prev', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('prorrogas_prev', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('revision_precios_prev', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('otros_conceptos_prev', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('inclusion_control_calidad', models.BooleanField(blank=True, null=True)),
                ('lugar_ejecucion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=1000, null=True)),
                ('medios_economica', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('medios_tecnica', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('mejora_criterio', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('objeto', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('obligacion_subcontratacion', models.BooleanField(blank=True, null=True)),
                ('otros_componentes', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
                ('penalidades_incumplimiento', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('plazo_ejecucion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('plazo_garantia', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=2000, null=True)),
                ('plazo_presentacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
                ('plazo_recepcion', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('plazo_maximo_prorrogas', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
                ('ampliacion_presentacion', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('porcentaje_max_subcontratacion', models.FloatField(blank=True, null=True)),
                ('posibilidad_prorroga', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('pag_info_criterios', models.IntegerField(blank=True, null=True)),
                ('regimen_penalidades', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('revision_precios', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('sistema_precios', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=1000, null=True)),
                ('subasta_electronica', models.BooleanField(blank=True, null=True)),
                ('subcontratacion_criterio', models.BooleanField(blank=True, null=True)),
                ('tareas_criticas', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('unidad_encargada', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('num_incursas_anormalidad', models.IntegerField(blank=True, null=True)),
                ('num_invitadas', models.IntegerField(blank=True, null=True)),
                ('num_seleccionadas', models.IntegerField(blank=True, null=True)),
                ('num_licitadores', models.IntegerField(blank=True, null=True)),
                ('num_excluidas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Licitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('id_licitacion', models.IntegerField()),
            ],
            options={
                'db_table': 'Links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id_participacion', models.AutoField(primary_key=True, serialize=False)),
                ('importe_ofertado_sin_iva', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('importe_ofertado_con_iva', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('excluida', models.BooleanField(blank=True, null=True)),
                ('anormalidad_economica', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Participaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrato',
            fields=[
                ('id_tipo_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_contrato', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'TipoContrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipolink',
            fields=[
                ('id_tipo_link', models.AutoField(primary_key=True, serialize=False)),
                ('texto_tipo_link', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'TipoLink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoprocedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_procedimiento', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'TipoProcedimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipotramitacion',
            fields=[
                ('id_tramitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tramitacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'TipoTramitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Valoraciones',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
