# Generated by Django 3.2.25 on 2024-07-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240705_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
