# Generated by Django 3.2.25 on 2024-08-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
